"""Checks of the PDF laid out from a monthly report's Markdown.

Run: python3 -m unittest discover -s tests
"""

import hashlib
import os
import re
import sys
import unittest

sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "tools"))

import font_metrics as metrics  # noqa: E402
import report_pdf  # noqa: E402

MD = """# Monthly report: March 2026

BTC-1, the record of reout.

- Month: 2026-03
- Record inception: 2026-03-01

## 1. Returns

|  | Month | Since record inception |
|---|---|---|
| Time-weighted return, as traded | −1.78% | +2.00% |
| Money-weighted return | — | −7.05%, for the period |

### Changes

Figures come from `data/monthly.csv` and are listed in part 8.

---

Generated by `tools/monthly_report.py`.
"""


def pdf(md=MD):
    return report_pdf.render(md, "reports/2026-03.md", hashlib.sha256(md.encode()).hexdigest())


def pages(data):
    return int(re.search(rb"/Type /Pages /Kids \[[^\]]*\] /Count (\d+)", data).group(1))


def in_colour(data, rgb):
    """What is drawn in one colour, as it is written in the file."""
    return re.findall(report_pdf.colour(rgb).encode()
                      + rb"\nBT /F\d [\d.]+ Tf [-\d.]+ Tc [\d.]+ [\d.]+ Td \(((?:\\.|[^\\)])*)\) Tj", data)


class Rendering(unittest.TestCase):

    def test_the_same_markdown_gives_the_same_bytes(self):
        self.assertEqual(pdf(), pdf())

    def test_another_markdown_gives_another_file(self):
        self.assertNotEqual(pdf(), pdf(MD.replace("+2.00%", "+2.01%")))

    def test_the_file_is_a_pdf_whose_cross_references_point_at_its_objects(self):
        data = pdf()
        self.assertTrue(data.startswith(b"%PDF-1.4\n"))
        self.assertTrue(data.endswith(b"%%EOF\n"))
        start = int(re.search(rb"startxref\n(\d+)\n%%EOF\n$", data).group(1))
        self.assertTrue(data[start:].startswith(b"xref\n"))
        offsets = re.findall(rb"(\d{10}) 00000 n ", data[start:])
        self.assertGreater(len(offsets), 6)
        for number, offset in enumerate(offsets, start=1):
            self.assertTrue(data[int(offset):].startswith(b"%d 0 obj\n" % number), number)
        for stream in re.finditer(rb"<< /Length (\d+) >>\nstream\n", data):
            end = stream.end() + int(stream.group(1))
            self.assertEqual(data[end:end + 10], b"\nendstream")

    def test_the_file_carries_no_date(self):
        self.assertNotIn(b"CreationDate", pdf())
        self.assertNotIn(b"ModDate", pdf())

    def test_the_figures_are_drawn_as_text(self):
        data = pdf()
        for text in (b"(Time-weighted return, as traded)", b"(+2.00%)", b"(BTC-1, the record of reout.)"):
            self.assertIn(text, data)

    def test_a_minus_sign_is_drawn_as_itself(self):
        # WinAnsi has no minus sign, so the faces carry it at the one code it
        # leaves for a control character, and the report draws that code.
        data = pdf()
        self.assertIn(b"(\\1771.78%)", data)
        self.assertNotIn(b"(-1.78%)", data)
        self.assertIn(b"/Differences [127 /minus]", data)

    def test_a_bold_span_is_drawn_in_the_bold_face_and_its_markers_are_not(self):
        data = pdf(MD.replace("BTC-1, the record", "**BTC-1**, the record"))
        self.assertRegex(data, rb"/F2 [\d.]+ Tf [-\d.]+ Tc [\d.]+ [\d.]+ Td \(BTC-1\) Tj")
        # The faces are embedded whole, so an asterisk may stand anywhere in
        # their bytes. What matters is that none of them is drawn.
        drawn = re.findall(rb"Td \(((?:\\.|[^\\)])*)\) Tj", data)
        self.assertNotIn(b"*", b"".join(drawn))

    def test_what_a_reader_copies_is_in_the_mono_and_a_figure_in_the_text_face(self):
        data = pdf()
        mono = report_pdf.RESOURCE["code"].encode()
        text = report_pdf.RESOURCE["figure"].encode()
        self.assertEqual(report_pdf.ROLES["figure"], report_pdf.ROLES["text"])
        self.assertRegex(data, rb"/" + mono + rb" [\d.]+ Tf [-\d.]+ Tc [\d.]+ [\d.]+ Td \(data/monthly.csv\) Tj")
        self.assertRegex(data, rb"/" + text + rb" [\d.]+ Tf [-\d.]+ Tc [\d.]+ [\d.]+ Td \(\+2.00%\) Tj")
        # The hash of the Markdown in the foot of every page is copied, so it is in the mono too.
        digest = hashlib.sha256(MD.encode()).hexdigest().encode()
        self.assertRegex(data, rb"/" + mono + rb" [\d.]+ Tf [-\d.]+ Tc [\d.]+ [\d.]+ Td \(" + digest + rb"\) Tj")

    def test_a_character_the_mono_does_not_carry_stops_the_rendering(self):
        # The mono carries ASCII alone; the text face carries all of WinAnsi.
        # An \u00e9 is byte 233 in WinAnsi, which the file writes as the octal escape \351.
        self.assertIn(b"face: caf\\351.", pdf("Set in the text face: caf\u00e9.\n"))
        with self.assertRaises(SystemExit):
            pdf("A code span: `caf\u00e9`.\n")

    def test_the_faces_are_embedded_as_the_repository_holds_them(self):
        data = pdf()
        self.assertEqual(data.count(b"/FontFile2"), len(report_pdf.EMBEDDED))
        for face in set(report_pdf.ROLES.values()):
            with open(os.path.join(report_pdf.FOLDER, face + ".ttf"), "rb") as f:
                ttf = f.read()
            self.assertEqual(hashlib.sha256(ttf).hexdigest(), metrics.FACES[face]["sha256"])
            self.assertIn(ttf, data)

    def test_the_letter_spacing_is_stated_by_every_line_drawn(self):
        # A text object inherits the spacing of the one before it, so a line set
        # with tracking would widen every line drawn after it on the page.
        objects = re.findall(rb"BT (.*?) ET", pdf(), re.S)
        self.assertTrue(objects)
        for ops in objects:
            self.assertRegex(ops, rb"^/F\d [\d.]+ Tf [-\d.]+ Tc [\d.]+ [\d.]+ Td \(")

    def test_the_brand_colour_marks_the_name_a_section_number_and_a_gain_and_nothing_else(self):
        drawn = in_colour(pdf(), report_pdf.GREEN)
        self.assertIn(b".", drawn)                 # the full stop of the wordmark
        self.assertIn(b"1. ", drawn)               # the number a section is known by
        self.assertIn(b"+2.00%", drawn)            # a return that is a gain
        for text in drawn:
            self.assertRegex(text, rb"^(\.|\d+\.\s+|\+[\d.,]+%?)$")

    def test_a_negative_figure_is_drawn_in_the_loss_colour_and_nothing_else_is(self):
        drawn = in_colour(pdf(), report_pdf.LOSS)
        self.assertIn(b"\\1771.78%", drawn)
        for text in drawn:
            self.assertTrue(text.startswith(b"\\177"), text)

    def test_the_benchmark_keeps_a_colour_of_its_own(self):
        # It is a series of its own, and not the account's gain or loss.
        md = ("# Daily\n\n| Date (UTC) | Return | Benchmark return |\n|---|---|---|\n"
              "| 2026-11-02 | +1.25% | −0.75% |\n")
        drawn = in_colour(pdf(md), report_pdf.BENCHMARK)
        self.assertEqual(drawn, [b"\\1770.75%"])
        self.assertIn(b"+1.25%", in_colour(pdf(md), report_pdf.GREEN))

    def test_the_label_of_a_report_is_stated_in_the_faint_ink_and_not_the_brand_colour(self):
        # A label says what the report is; it is not a mark of the brand.
        label = "Correction notice"
        data = report_pdf.render(MD, "reports/2026-10.correction-1.md", "0" * 64, label=label)
        drawn = report_pdf.escape(report_pdf.encode(label)).encode()
        self.assertIn(drawn, in_colour(data, report_pdf.FAINT))
        self.assertNotIn(drawn, in_colour(data, report_pdf.GREEN))

    def test_the_terms_after_the_title_are_set_as_a_specification(self):
        data = pdf()
        self.assertIn(b"(Month)", data)
        self.assertIn(b"(2026-03)", data)
        self.assertNotIn(b"(Month: 2026-03)", data)

    def test_every_page_states_the_hash_of_the_markdown(self):
        md = MD + "".join(f"\nParagraph {i} of a long report, to fill more than one page.\n" for i in range(120))
        data = pdf(md)
        self.assertGreater(pages(data), 1)
        digest = hashlib.sha256(md.encode()).hexdigest().encode()
        self.assertEqual(data.count(b"(" + digest + b")"), pages(data))

    def test_the_head_says_where_to_check_the_report_and_links_there(self):
        md = MD.replace("- Record inception: 2026-03-01\n", "- Record inception: 2026-03-01\n"
                        + "".join(f"- {name}: `{shown}`\n" for name, shown, _ in report_pdf.VERIFY))
        md += "\n" + "\n".join(f"Paragraph {k} of a long report, so that it runs to a second page." for k in range(80))
        data = pdf(md)
        self.assertGreater(pages(data), 1)
        for name, shown, uri in report_pdf.VERIFY:
            self.assertIn(b"(" + name.encode() + b") Tj", data)            # a term of the head
            self.assertEqual(data.count(b"(" + shown.encode() + b") Tj"), 1)
            self.assertEqual(data.count(b"/URI (" + uri.encode() + b")"), 1)
        # Both on the first page, lying on it, and no other page carries a link.
        self.assertEqual(len(re.findall(rb"/Annots \[\d+ 0 R \d+ 0 R\]", data)), 1)
        for rect in re.findall(rb"/Subtype /Link /Rect \[([\d. ]+)\]", data):
            x1, y1, x2, y2 = map(float, rect.split())
            self.assertTrue(report_pdf.LEFT <= x1 < x2 <= report_pdf.PAGE_W - report_pdf.RIGHT)
            self.assertGreater(y1, report_pdf.PAGE_H / 2)

    def test_a_report_without_the_addresses_carries_no_link(self):
        self.assertNotIn(b"/Annots", pdf())

    def test_a_long_table_continues_on_the_next_page_under_its_header(self):
        md = "# Daily\n\n| Date (UTC) | Return |\n|---|---|\n" + "".join(f"| day {i} | +0.10% |\n" for i in range(200))
        data = pdf(md)
        self.assertGreater(pages(data), 1)
        self.assertEqual(data.count(b"(Date \\(UTC\\))"), pages(data))
        self.assertIn(b"(day 199)", data)

    def test_a_mark_that_cannot_start_a_line_keeps_the_word_before_it(self):
        # A code span and the words after it are separate runs, so a line may
        # break between them. The width here is measured so that the break falls
        # exactly there: the comma must not be left to open the next line.
        size = 9.4
        runs = report_pdf.spans("listed in `reports/2026-10.sha256`, which is anchored", "text")
        upto = sum(report_pdf.advance(role, text, size) for role, text in runs[:2])
        lines = report_pdf.wrap(runs, size, upto + 1.0)
        # The break falls at the span, which is the case this rule is about.
        self.assertGreater(len(lines), 1)
        self.assertTrue(lines[1][0][1].startswith("reports/2026-10.sha256"), lines[1])
        for line in lines:
            self.assertFalse(line[0][1].startswith(tuple(report_pdf.CLINGING)), line)

    def test_the_widest_cell_of_a_column_is_not_broken(self):
        md = ("# Narrow\n\n| Date (UTC) | Return | Index |\n|---|---|---|\n"
              "| 2026-11-02 | +1.25% | 101.25 |\n| 2026-11-09 | −4.50% | 96.69 |\n")
        data = pdf(md)
        for whole in (b"(Date \\(UTC\\))", b"(+1.25%)", b"(\\1774.50%)", b"(2026-11-09)", b"(101.25)"):
            self.assertIn(whole, data)
        self.assertNotIn(b"(%)", data)

    def test_a_wide_table_stays_within_the_page(self):
        long_text = "a finding written at length " * 20
        md = f"# Wide\n\n| When | Finding |\n|---|---|\n| 2026-03-02 | {long_text.strip()} |\n| 2026-03-03 | {'x' * 400} |\n"
        data = pdf(md)
        limit = report_pdf.PAGE_W - report_pdf.RIGHT
        for font, size, x, text in re.findall(rb"/(F\d) ([\d.]+) Tf ([\d.]+) [\d.]+ Td \(((?:\\.|[^\\)])*)\) Tj", data):
            shown = re.sub(rb"\\(.)", rb"\1", text).decode("latin-1")
            kind = {b"F1": "regular", b"F2": "bold", b"F3": "code"}[font]
            self.assertLessEqual(float(x) + report_pdf.advance(kind, shown, float(size)), limit + 0.01, shown[:30])

    def test_a_character_the_standard_fonts_cannot_draw_stops_the_rendering(self):
        with self.assertRaises(SystemExit):
            pdf("# 가\n")

    def test_markdown_the_report_does_not_write_stops_the_rendering(self):
        for other in ("#### deeper\n", "* item\n", "> quoted\n", "```\ncode\n```\n", "1. first\n", "<b>x</b>\n"):
            with self.assertRaises(SystemExit, msg=other):
                pdf(other)

    def test_an_unclosed_code_span_stops_the_rendering(self):
        with self.assertRaises(SystemExit):
            pdf("A `span that never ends.\n")

    def test_an_unclosed_bold_span_stops_the_rendering(self):
        with self.assertRaises(SystemExit):
            pdf("A **span that never ends.\n")


if __name__ == "__main__":
    unittest.main()
